### ISSUE TITLE
Embedded PDF support

### ISSUE THREAD

**Issue by via-lactea7** [kitschpatrol/yanki-obsidian#17]
I want to make anki card that includes a piece of pdf. 

So I use excalidraw and pdf++. 

it's one of my obsidian anki cards. 

![[pdf#page=5]] 
Question 
---
Answer 

but in anki, I can't see the pdf 🥲

what should I do for this?

**Comment by kitschpatrol** [comment]
Hi, thanks for trying the plugin.

Yanki does not support PDF embedding because Anki does not support PDF rendering — or at least it does not support it  without loading extra JavaScript or depending on additional Anki plugins, neither of which I want to do or support in Yanki.

Because of this limitation, Yanki makes a best-effort to provide a hyperlink to embedded PDF in the resulting Anki cards instead.

(This whole business of embedding is also a non-standard Markdown behavior that's mostly specific to Obsidian... and while I've made significant efforts to replicate almost all of Obsidian's special Markdown features, there are a few edge cases like this that don't make sense to support since Anki can't really handle them anyway.)

For a work-around, you could find a way to render the PDF to an image and then embed that in your note instead. There might be a plugin to do this, or you could write a script to do it. Yanki should sync embedded image assets without complaint, and Anki will know how to render them.

I'd consider accepting a PR adding PDF-to-image pre-rendering directly to Yanki, but don't have time to implement it myself at the moment, so I'm closing this issue.

**Comment by kitschpatrol** [comment]
Adding a link to the equivalent issue you opened on the ObsidianToAnki repo:

https://github.com/ObsidianToAnki/Obsidian_to_Anki/discussions/614
