### ISSUE TITLE
Use Obsidian note's filename as content for front of Anki card

### ISSUE THREAD

**Issue by peligrini603** [kitschpatrol/yanki-obsidian#18]
on the gif  presentation of the app it looks like the recto of the anki flash card is the filename of the obsidian note and the verso of the anki flashcard is the content of obsidian note.

It is exactly what i would like to obtain. 

i use 1.6.7 obsidian on OsX

For now, the recto of my flashcards remains "empty" and yanki seems to totally ignore the title of the obsidian note

Can yanki file automatically the recto of the flashcard with the filename of the obsidian note ?

Is it possible to obtain directly a basic flash card containing just the title of the obsidian note on the recto and the content of the note on the verso ?

Thank  you in advance for your answers to my question

**Comment by kitschpatrol** [comment]
Hi, thanks for using the plugin and for posing this question. I hope you don't mind I've edited the title to match my understanding of your request.

Yanki does not support using the note's filename as part of the content of the generated card. 

Filenames have length, cross-platform character constraints, uniqueness requirements, and formatting limitations that make them a less than ideal place to write text content for your cards.

This is not a feature I'm going to add — but there are some things you can do about it:

## Solution 1 _(recommended)_

If you're annoyed with keeping the Obsidian note's filename in sync with the front / recto content inside the note, then Yanki Obsidian has a built-in feature to automatically update the Obsidian filename to match wither the front / rector or back / verso content of the card. With this approach you'll edit the note's content instead of its filename, and the filename will update automatically.

Details from the [readme](https://github.com/kitschpatrol/yanki-obsidian#readme):

> ### Note name management
>   The "one Obsidian note = one Anki note" premise can make for a lot of individual note files, and thinking up and renaming notes as their content is revised can be tedious. So, if you want, Yanki can manage the names of your note files based on their content.
>   
>   Yanki looks inside each note, and extracts either the text of the "prompt" (e.g. the front of the card in most cases), or the "response" (e.g. the back of the card in most cases) to use as the filename. Truncation, deduplication, and sanitization are all taken care of.
>   
>   Edge cases are carefully managed to ensure that there's always some kind of best-effort semantically valuable file name assigned.

And...

> #### Automatic note name settings
> 
> ##### Automatic note names
> 
> When enabled, local note files will be renamed to match their content. This is useful if you want to have semantically reasonable note file names without the exertion of managing note titles yourself.
> 
> If the prompt or response has multiple lines, only the first line of text is considered.
> 
> The file renaming pass runs as part of every sync to Anki, and only affects notes inside a [watched folder](#watched-folder-list). Even if the Anki application is closed, attempting a sync will still update the local flashcard note file names, and modifying the content of a watched flashcard note will update its title immediately.
> 
> There are some great community plugins dedicated to content-driven file naming, like Rey Christian's [Auto Filename](https://github.com/rcsaquino/obsidian-auto-filename) plugin, but this feature is built into Yanki since the renaming process can be more precise when the structure of flashcard notes is understood.
> 
> _Default: Off_
> 
> ##### Name mode
> 
> If [Automatic note names](#automatic-note-names) is enabled, this setting allows you to prioritize which part of the flashcard note should be used for the automatic note file name.
> 
> - **Prompt**\
>   This option sets the note title to the first line of text Anki shows you during a review session — usually the front of the card.
> 
> - **Response**\
>   This option sets the note title to the first line of text revealed in Anki after a tap or click — usually the back of the card, or the elided text of a cloze card, or the answer text of a type in the answer card.
> 
> For edge cases, like notes with empty prompt content or no response content, Yanki will fall back to the other parts of the card to try provide a semantically useful title for the note. If, after every effort, no reasonable title can be identified, then "Untitled" will be used as the note title.
> 
> Sanitization, truncation, and sequential numbering of duplicate note titles are all handled automatically by Yanki.
> 
> _Default: Prompt_
> 
> _(But note that the [Automatic note names](#automatic-note-names) toggle must be enabled for this to take effect.)_
> 
> ##### Maximum note name length
> 
> Yanki will truncate long automatic file names with ellipses. This setting allows you to specify, in characters, how long of an automatic title you would like (exclusive of the truncation ellipses and file extension). Note that a (generous) upper limit is enforced to comply with operating system limitations.
> 
> _Default: 60 characters_


## Solution 2

Use an Obsidian plugin like [Filename Heading Sync](https://github.com/dvcrn/obsidian-filename-heading-sync) [Title renamer](https://github.com/stroiman/obsidian-title-sync) to automatically set the top heading of your note to the file name.

With this approach you edit the file name and then the note content updates.

Both of these seem to only sync to an `h1` / `#` element inside your note, in which case you might want to modify your note CSS to improve legibility if your titles are long. (Or try to find a plugin that can set the first row of note text instead of the first `h1`

However, I don't recommend this approach for all the reasons I first mentioned about the problems with drafting content in file names.


---

I'm closing this issue since it's not a planned enhancement for Yanki, but feel free to comment if you have follow-up questions.

**Comment by peligrini603** [comment]
Thank you for your quick answer and thank you for this very useful plug in  

To make sure i understand well your answer :  there is no solution to get directly with yanki the same result as shown in the two images below
(since my note titles match exactly the content of the note i don't want to rename them)

<img width="1336" alt="Image 2" src="https://github.com/user-attachments/assets/0b594ff1-0213-4ba5-9aad-89ae9a9d58fb">
<img width="1047" alt="Image" src="https://github.com/user-attachments/assets/412517e9-afd0-4743-abd4-329878193851">

**Comment by kitschpatrol** [comment]
The filename and the front of the card in the screenshot match in the screenshots because I've enabled the **automatic note names** option in the Yanki plugin settings as I explained in "Solution 1" of my initial response.

You can explore the demo vault used in the screenshots here:
https://github.com/kitschpatrol/yanki-obsidian/tree/main/examples/Demo%20Vault

And specifically the card you're showing here:
https://github.com/kitschpatrol/yanki-obsidian/blob/main/examples/Demo%20Vault/Features/Infer%20Anki%20note%20type%20from%20Markdown%20structure.md

Let me see if I can give you a really simple example...

Say you create a new note like this, in a file named `some note.md`:

```markdown
Front

---

Back
```

Then in the Yanki plugin settings you enable automatic note names:

![Screenshot 2024-09-21 at 13 33 58 of Obsidian - New tab - Vault - Obsidian v1 6 7@2x](https://github.com/user-attachments/assets/fc5aaa8c-fd2e-45d3-b934-fe55205d2845)

Now when you sync, the note's file _will be renamed to match its prompt / front / recto_, so now you'll have a note with the filename `Front.md` instead of  `some note.md`.

It's better to let the content of the note drive the filename, instead of having the content of the filename drive the note for all the reasons I already listed:

- Length limits
- Coss-platform character constraints
- Uniqueness requirements

The automatic note name feature in Yanki takes care of all of these concerns for you, and makes it easy to keep your notes names in sync with their content.

All of this info is already in the readme.

**Comment by peligrini603** [comment]
Thanks a lot for having taking the time to answer me.
Have a good day

Le sam. 21 sept. 2024 à 19:40, Eric Mika ***@***.***> a
écrit :
