### ISSUE TITLE
If a YAML section exists before note synchronization, the separator --- used to divide the YAML and content will be considered as a card symbol

### ISSUE THREAD

**Issue by Hwenyi** [kitschpatrol/yanki-obsidian#21]
Within the synchronized card folder, there are some notes that already existed, which include YAML. The --- delimiter used to separate the body text from the YAML is mistakenly identified as an Anki marker, causing non-card notes to be synchronized.

![image](https://github.com/user-attachments/assets/10acf230-4df4-45c0-bd20-12a67357995c)

This test card serves as an example. Within the Anki folder, there are some regular notes (not cards) that were originally stored in the YAML section. If synchronization is performed, it will result in making an Anki card without a back side. (At the same time, I don't want these regular notes to be turned into anki cards.)

![image](https://github.com/user-attachments/assets/d5d60aa8-70f3-4734-b75f-b8ab42a7d2ec)

![image](https://github.com/user-attachments/assets/075afe51-b2bc-4611-99d1-fd4c441c7ecd)

I'm not sure if this is a feature or a bug. Thank you for the yanki plugin and all the effort you've put into it. If possible, I hope this issue can be addressed (if it is indeed a bug).

**Comment by kitschpatrol** [comment]
Hi Lien thanks for using the plugin and for sharing this issue.

I can see why this is confusing, but it's actually working as designed.

It's subtle, but Yanki is not mistakenly detecting the `---` in the frontmatter as a card delimiter (otherwise "something test" would be on the _reverse_ of the resulting card), instead it's ignoring the frontmatter completely and seeing a card _without_ a `---` delimiter in the watched folder, and treating it as a basic card with no content on the reverse side.

With Yanki, *ALL* Markdown notes in a watched folder will be turned into Anki notes one way or another, no matter the structure of their content. If you don't want certain notes to be turned into cards, they have to be stored outside the watched folder(s).

I can see the advantages of a more granular note selection paradigm instead of the folder-based approach, but I don't believe it's worth the complexity trade-off in Yanki.

This is related to the discussion in #16.
