### ISSUE TITLE
Suggestion: Option for allowing the front of the flashcard to be the title of the note, eliminating for repetitive formatting for my flaschards

### ISSUE THREAD

**Issue by DawidKmiec** [kitschpatrol/yanki-obsidian#24]
Makes it better when linking flashcards within obsidian, would very appreciate if possible.

**Comment by kitschpatrol** [comment]
Hi, thank you for your suggestion.

It's come up before, so please see [this issue thread](https://github.com/kitschpatrol/yanki-obsidian/issues/18) for an in-depth discussion of how to configure the plugin's built-in note name synchronization functionality, and for an explanation of the technical reasons Yanki is designed to derive filenames from note content instead of the other way around.
